"""Surface-contract conformance for this client.

Generated by the surface-contract harness; see contract/README.md.
Runs under pytest or as `python3 surface_contract_test.py`. No third-party dependencies.
"""

import os
import subprocess
import sys
import unittest

LANGUAGE = 'reactive-dart'


def _repo_root():
    d = os.path.dirname(os.path.abspath(__file__))
    while not os.path.exists(os.path.join(d, "contract", "surface.contract.json")):
        parent = os.path.dirname(d)
        if parent == d:
            raise RuntimeError("no surface contract found above " + __file__)
        d = parent
    return d


class SurfaceContractTest(unittest.TestCase):
    def test_client_exports_the_declared_surface(self):
        root = _repo_root()
        proc = subprocess.run(
            [sys.executable, os.path.join(root, "contract", "bin", "check_surface.py"),
             "--lang", LANGUAGE],
            cwd=root, capture_output=True, text=True,
        )
        self.assertEqual(
            proc.returncode, 0,
            "clients/%s violates the exported-interface contract:\n%s%s"
            % (LANGUAGE, proc.stdout, proc.stderr),
        )


if __name__ == "__main__":
    unittest.main()
