package opto_syncclient

// Surface-contract conformance for this client.
// Generated by the surface-contract harness; see contract/README.md.

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

func surfaceContractRoot(t *testing.T) string {
	t.Helper()
	d, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(d, "contract", "surface.contract.json")); err == nil {
			return d
		}
		parent := filepath.Dir(d)
		if parent == d {
			t.Fatal("no surface contract found above the working directory")
		}
		d = parent
	}
}

func TestSurfaceContract(t *testing.T) {
	root := surfaceContractRoot(t)
	cmd := exec.Command("python3", filepath.Join(root, "contract", "bin", "check_surface.py"), "--lang", "golang")
	cmd.Dir = root
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("clients/golang violates the exported-interface contract:\n%s", out)
	}
}
