#!/usr/bin/env sh
# Pre-publish gate for clients/swift.
#
# Run this immediately before uploading this client to its package registry —
# from publish.sh, from a release workflow, or by hand. It refuses to let a
# client ship whose exported interface has drifted from
# contract/surface.contract.json.
#
# Generated by the surface-contract harness; see contract/README.md.
set -eu

dir="$(cd "$(dirname "$0")" && pwd)"
root="$dir"
while [ ! -f "$root/contract/surface.contract.json" ]; do
    parent="$(dirname "$root")"
    [ "$parent" = "$root" ] && { echo "prepublish: no surface contract found above $dir" >&2; exit 2; }
    root="$parent"
done

exec "$root/contract/bin/prepublish-guard.sh" "swift"
