//! Surface-contract conformance for this client.
//! Generated by the surface-contract harness; see contract/README.md.

use std::path::{Path, PathBuf};
use std::process::Command;

fn repo_root() -> PathBuf {
    let mut dir: &Path = Path::new(env!("CARGO_MANIFEST_DIR"));
    loop {
        if dir.join("contract").join("surface.contract.json").exists() {
            return dir.to_path_buf();
        }
        dir = dir
            .parent()
            .expect("no surface contract found above CARGO_MANIFEST_DIR");
    }
}

#[test]
fn exports_the_declared_surface() {
    let root = repo_root();
    let out = Command::new("python3")
        .arg(root.join("contract").join("bin").join("check_surface.py"))
        .arg("--lang")
        .arg("rust")
        .current_dir(&root)
        .output()
        .expect("python3 is required to verify the surface contract");
    assert!(
        out.status.success(),
        "clients/rust violates the exported-interface contract:\n{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
}
